export const foodList = [
  {
    id: 1,
    imageUrl: "./assets/foodImages/space-food_006.jpg",
    name: "日清スペースチキンラーメン",
    description:  "お湯を注入して食べる",
    contents: "35.7g（1包当り）（麺6.3ｇ×3個）",
    nutorition: { calorie: 153, vidaminD: 20 },
    maker:  "日清食品ホールディングス株式会社",
    stocked: 20,
  },
  {
    id: 2,
    imageUrl: "./assets/foodImages/space-food_005.jpg",
    name: "スペース日清焼そばU.F.O.",
    description:  "お湯を注入して食べる",
    contents: "36.9g（1包当り）（麺4.7ｇ×5個）",
    nutorition: { calorie: 168, vidaminD: 20 },
    maker:  "日清食品ホールディングス株式会社",
    stocked: 20,
  },
  {
    id: 3,
    imageUrl: "./assets/foodImages/space-food_008.jpg",
    name: "日清スペースキーマカレーメシ",
    description:  "お湯を注入して食べる",
    contents: "74.8g（1包当り）",
    nutorition: { calorie: 331, vidaminD: 20 },
    maker:  "日清食品ホールディングス株式会社",
    stocked: 20,
  },
  {
    id: 4,
    imageUrl: "./assets/foodImages/space-food_007.jpg",
    name: "日清スペースハヤシメシ",
    description:  "お湯を注入して食べる",
    contents: "76.2g（1包当り）",
    nutorition: { calorie: 335, vidaminD: 20 },
    maker:  "日清食品ホールディングス株式会社",
    stocked: 20,
  },
  {
    id: 5,
    imageUrl: "./assets/foodImages/space-food_042.jpg",
    name: "イベリコ豚とマッシュルームのカレー（レトルトカレー宇宙食）",
    description:  "専用の加温器で温めて食べる",
    contents: "180g（1包当り）",
    nutorition: { calorie: 285, vidaminD: 20 },
    maker:  "ハウス食品株式会社",
    stocked: 20,
  },
  {
    id: 6,
    imageUrl: "./assets/foodImages/IMG_1384a.jpg",
    name: "スペースからあげクン",
    description:  "そのまま食べる",
    contents: "12g（1包あたり）",
    nutorition: { calorie: 66.6, vidaminD: 20 },
    maker:  "株式会社ローソン",
    stocked: 20,
  },
  {
    id: 7,
    imageUrl: "./assets/foodImages/IMG_1392a.jpg",
    name: "森永ミルク生活（宇宙用）",
    description:  "水を注入して飲む",
    contents: "20g（1包あたり）",
    nutorition: { calorie: 95, vidaminD: 20 },
    maker:  "森永乳業株式会社",
    stocked: 20,
  },
  {
    id: 8,
    imageUrl: "./assets/foodImages/70861.JPG",
    name: "スペースまるとっとアジ（燻製しお味）",
    description:  "そのまま食べる",
    contents: "50ｇ（1包あたり）",
    nutorition: { calorie: 95, vidaminD: 20 },
    maker:  "株式会社キシモト",
    stocked: 20,
  },
  {
    id: 9,
    imageUrl: "./assets/foodImages/70731.JPG",
    name: "ちりめん山椒",
    description:  "そのまま食べる",
    contents: "10ｇ（1包あたり）",
    nutorition: { calorie: 24, vidaminD: 20 },
    maker:  "宝食品株式会社",
    stocked: 20,
  },
  {
    id: 10,
    imageUrl: "./assets/foodImages/photo_032.JPG",
    name: "ホテイやきとり（たれ味）宇宙用",
    description:  "そのまま、または専用の加温器で温めて食べる",
    contents: "96～105g（1包当り）",
    nutorition: { calorie: 196, vidaminD: 20 },
    maker:  "株式会社ホテイフーズコーポレーション",
    stocked: 20,
  },
  {
    id: 11,
    imageUrl: "./assets/foodImages/photo_033.JPG",
    name: "ホテイやきとり（柚子こしょう味）宇宙用",
    description:  "そのまま、または専用の加温器で温めて食べる",
    contents: "91～100g（1包当り）",
    nutorition: { calorie: 136, vidaminD: 20 },
    maker:  "株式会社ホテイフーズコーポレーション",
    stocked: 20,
  },
  {
    id: 12,
    imageUrl: "./assets/foodImages/photo_014.JPG",
    name: "宇宙食 特濃ミルク8.2",
    description:  "そのまま食べる",
    contents: "21.8g（1包（5個入り）当り）",
    nutorition: { calorie: 92, vidaminD: 20 },
    maker:  "味覚糖株式会社",
    stocked: 20,
  },
  {
    id: 13,
    imageUrl: "./assets/foodImages/photo_024.JPG",
    name: "味付海苔",
    description:  "そのまま食べる",
    contents: "3.8g（2袋（1袋8切5枚入り）当たり）",
    nutorition: { calorie: 13.8, vidaminD: 20 },
    maker:  "株式会社山本海苔店",
    stocked: 20,
  },
  {
    id: 14,
    imageUrl: "./assets/foodImages/photo_034.JPG",
    name: "サバ醤油味付け缶詰",
    description:  "そのまま、または専用の加温器で温めて食べる",
    contents: "120±10g",
    nutorition: { calorie: 238, vidaminD: 20 },
    maker:  "福井県立若狭高等学校",
    stocked: 20,
  },
  {
    id: 15,
    imageUrl: "./assets/foodImages/photo_001.JPG",
    name: "SPACEビスコ",
    description:  "そのまま食べる",
    contents: "16.5g（2袋（各2枚入り）当たり）",
    nutorition: { calorie: 78, vidaminD: 20 },
    maker:  "江崎グリコ株式会社",
    stocked: 20,
  },
  {
    id: 16,
    imageUrl: "./assets/foodImages/photo_002.JPG",
    name: "切り餅",
    description:  "専用の加温器で温めて食べる",
    contents: "83～93g（1包（4個入り）当り）",
    nutorition: { calorie: 199, vidaminD: 20 },
    maker:  "越後製菓株式会社",
    stocked: 20,
  },
  {
    id: 17,
    imageUrl: "./assets/foodImages/photo_036.JPG",
    name: "キッコーマン宇宙生しょうゆ",
    description:  "つけて食べる",
    contents: "200ml",
    nutorition: { calorie: 14, vidaminD: 20 },
    maker:  "キッコーマン食品株式会社",
    stocked: 20,
  },
  {
    id: 18,
    imageUrl: "./assets/foodImages/photo_009.JPG",
    name: "亀田の柿の種（宇宙食）",
    description:  "そのまま食べる",
    contents: "35g（1包当り）",
    nutorition: { calorie: 168, vidaminD: 20 },
    maker:  "亀田製菓株式会社",
    stocked: 20,
  },
  {
    id: 19,
    imageUrl: "./assets/foodImages/photo_013.JPG",
    name: "ピーチゼリー",
    description:  "そのまま食べる",
    contents: "63g（1個当り）",
    nutorition: { calorie: 49, vidaminD: 20 },
    maker:  "ハウス食品株式会社",
    stocked: 20,
  },
  {
    id: 20,
    imageUrl: "./assets/foodImages/photo_003.JPG",
    name: "バランス栄養食ブロックタイプ（チーズ味）",
    description:  "そのまま食べる",
    contents: "40g（1包当り）",
    nutorition: { calorie: 200, vidaminD: 20 },
    maker:  "大塚製薬株式会社",
    stocked: 20,
  },
  {
    id: 21,
    imageUrl: "./assets/foodImages/photo_004.JPG",
    name: "イオンドリンク",
    description:  "水を注入して食べる",
    contents: "11.1g（1包当り）",
    nutorition: { calorie: 43.2, vidaminD: 20 },
    maker:  "大塚製薬株式会社",
    stocked: 20,
  },
  {
    id: 22,
    imageUrl: "./assets/foodImages/photo_023.JPG",
    name: "プルーンエキストラクト",
    description:  "そのまま食べる",
    contents: "60g（1包（2本入り）当たり）",
    nutorition: { calorie: 165.6, vidaminD: 20 },
    maker:  "三基商事株式会社",
    stocked: 20,
  },
  {
    id: 23,
    imageUrl: "./assets/foodImages/photo_020.JPG",
    name: "キシリトールガム（ライムミント）",
    description:  "そのまま食べる",
    contents: "21g（1包（14粒入り）当たり）",
    nutorition: { calorie: 42, vidaminD: 20 },
    maker:  "株式会社ロッテ",
    stocked: 20,
  },
  {
    id: 24,
    imageUrl: "./assets/foodImages/macherel_misosoup.jpg",
    name: "サバの味噌煮",
    description:  "そのまま、または専用の加温器で温めて食べる",
    contents: "110g（1包当り）",
    nutorition: { calorie: 325, vidaminD: 20 },
    maker:  "マルハニチロ株式会社",
    stocked: 20,
  },
  {
    id: 25,
    imageUrl: "./assets/foodImages/sardine_tomatosauce.jpg",
    name: "イワシのトマト煮",
    description:  "そのまま、または専用の加温器で温めて食べる",
    contents: "100g（1包当り）",
    nutorition: { calorie: 185, vidaminD: 20 },
    maker:  "マルハニチロ株式会社",
    stocked: 20,
  },
  {
    id: 26,
    imageUrl: "./assets/foodImages/macherel_pike_teriyakisauce.jpg",
    name: "サンマの蒲焼き",
    description:  "そのまま、または専用の加温器で温めて食べる",
    contents: "100g（1包当り）",
    nutorition: { calorie: 283, vidaminD: 20 },
    maker:  "マルハニチロ株式会社",
    stocked: 20,
  },
  {
    id: 27,
    imageUrl: "./assets/foodImages/images/photo_017.JPG",
    name: "粉末緑茶",
    description:  "お湯を注入して飲む",
    contents: "1.2g（1包当り）",
    nutorition: { calorie: 4, vidaminD: 20 },
    maker:  "三井農林株式会社",
    stocked: 20,
  },
  {
    id: 28,
    imageUrl: "./assets/foodImages/photo_018.JPG",
    name: "粉末ウーロン茶",
    description:  "お湯を注入して飲む",
    contents: "2.0g（1包当り）",
    nutorition: { calorie: 7, vidaminD: 20 },
    maker:  "三井農林株式会社",
    stocked: 20,
  },
  {
    id: 29,
    imageUrl: "./assets/foodImages/photo_021.JPG",
    name: "羊羹（小倉）",
    description:  "そのまま食べる",
    contents: "62g（1包当り）",
    nutorition: { calorie: 173, vidaminD: 20 },
    maker:  "山崎製パン株式会社",
    stocked: 20,
  },
  {
    id: 30,
    imageUrl: "./assets/foodImages/photo_022.JPG",
    name: "羊羹（栗）",
    description:  "そのまま食べる",
    contents: "62g（1包当り）",
    nutorition: { calorie: 175, vidaminD: 20 },
    maker:  "山崎製パン株式会社",
    stocked: 20,
  },
  {
    id: 31,
    imageUrl: "./assets/foodImages/photo_015.JPG",
    name: "黒飴",
    description:  "そのまま食べる",
    contents: "26.5g（1包（5個入り）当り）",
    nutorition: { calorie: 102, vidaminD: 20 },
    maker:  "ヤマザキビスケット株式会社",
    stocked: 20,
  },
  {
    id: 32,
    imageUrl: "./assets/foodImages/photo_016.JPG",
    name: "ミントキャンディー",
    description:  "そのまま食べる",
    contents: "20.5g（1包（5個入り）当り）",
    nutorition: { calorie: 79, vidaminD: 20 },
    maker:  "ヤマザキビスケット株式会社",
    stocked: 20,
  },
  {
    id: 33,
    imageUrl: "./assets/foodImages/photo_019.JPG",
    name: "わかめスープ",
    description:  "お湯を注入して食べる",
    contents: "6.4g（1包当り）",
    nutorition: { calorie: 19, vidaminD: 20 },
    maker:  "理研ビタミン株式会社",
    stocked: 20,
  },
  {
    id: 34,
    imageUrl: "./assets/foodImages/photo_005.JPG",
    name: "白飯",
    description:  "お湯を注入して食べる",
    contents: "62g（1包当り）（出来上り量：162g）",
    nutorition: { calorie: 228, vidaminD: 20 },
    maker:  "尾西食品株式会社",
    stocked: 20,
  },
  {
    id: 35,
    imageUrl: "./assets/foodImages/photo_006.JPG",
    name: "赤飯",
    description:  "お湯を注入して食べる",
    contents: "68g（1包当り） （出来上り量：143g）",
    nutorition: { calorie: 249, vidaminD: 20 },
    maker:  "尾西食品株式会社",
    stocked: 20,
  },
  {
    id: 36,
    imageUrl: "./assets/foodImages/photo_007.JPG",
    name: "山菜おこわ",
    description:  "お湯を注入して食べる",
    contents: "68g（1包当り）（出来上り量：168g）",
    nutorition: { calorie: 245, vidaminD: 20 },
    maker:  "尾西食品株式会社",
    stocked: 20,
  },
  {
    id: 37,
    imageUrl: "./assets/foodImages/photo_008.JPG",
    name: "おにぎり 鮭",
    description:  "お湯を注入して食べる",
    contents: "50g（1包当り）（出来上り量：125g）",
    nutorition: { calorie: 188, vidaminD: 20 },
    maker:  "尾西食品株式会社",
    stocked: 20,
  },
  {
    id: 38,
    imageUrl: "./assets/foodImages/mayonnaise.jpg",
    name: "マヨネーズ",
    description:  "そのまま食品にかける",
    contents: "50g（1包当り）",
    nutorition: { calorie: 350, vidaminD: 20 },
    maker:  "キユーピー株式会社",
    stocked: 20,
  },
  {
    id: 39,
    imageUrl: "./assets/foodImages/photo_035.JPG",
    name: "白がゆ",
    description:  "専用の加温器で温めて食べる",
    contents: "250g（1包当り）",
    nutorition: { calorie: 113, vidaminD: 20 },
    maker:  "キユーピー株式会社",
    stocked: 20,
  },
  {
    id: 40,
    imageUrl: "./assets/foodImages/ramen_soysauce.jpg",
    name: "日清スペースカップヌードル",
    description:  "お湯を注入して食べる",
    contents: "約35.6g（1包当り）（麺6.3g×3個）",
    nutorition: { calorie: 160, vidaminD: 20 },
    maker:  "日清食品ホールディングス株式会社",
    stocked: 20,
  },
  {
    id: 41,
    imageUrl: "./assets/foodImages/ramen_seafood.jpg",
    name: "日清スペースシーフードヌードル",
    description:  "お湯を注入して食べる",
    contents: "約34.9g（1包当り） （麺6.3g×3個）",
    nutorition: { calorie: 147, vidaminD: 20 },
    maker:  "日清食品ホールディングス株式会社",
    stocked: 20,
  },
  {
    id: 42,
    imageUrl: "./assets/foodImages/ramen_curry.jpg",
    name: "日清スペースカップヌードルカレー",
    description:  "お湯を注入して食べる",
    contents: "約45.6g（1包当り）（麺6.3g×3個）",
    nutorition: { calorie: 227, vidaminD: 20 },
    maker:  "日清食品ホールディングス株式会社",
    stocked: 20,
  },
  {
    id: 43,
    imageUrl: "./assets/foodImages/images/photo_012.JPG",
    name: "レトルト チキンカレー",
    description:  "専用の加温器で温めて食べる",
    contents: "140g（1包当り）",
    nutorition: { calorie: 125, vidaminD: 20 },
    maker:  "ハウス食品株式会社",
    stocked: 20,
  },
  {
    id: 44,
    imageUrl: "./assets/foodImages/photo_010.JPG",
    name: "レトルト ビーフカレー",
    description:  "専用の加温器で温めて食べる",
    contents: "140g（1包当り）",
    nutorition: { calorie: 130, vidaminD: 20 },
    maker:  "ハウス食品株式会社",
    stocked: 20,
  },
  {
    id: 45,
    imageUrl: "./assets/foodImages/photo_011.JPG",
    name: "レトルト ポークカレー",
    description:  "専用の加温器で温めて食べる",
    contents: "140g（1包当り）",
    nutorition: { calorie: 144, vidaminD: 20 },
    maker:  "ハウス食品株式会社",
    stocked: 20,
  }
];
